version: '3'

services:

  webserver:
    image: nginx:alpine
    ports:
      - "70:80"
    volumes:
      - ./src:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - db

  php:
    image: php:7.4-fpm
    volumes:
      - ./src:/var/www/html

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 9506213585
      MYSQL_DATABASE: gallows
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata: