version: "3"

services:

  db:
    image: mysql:8
    volumes:
      - dbdata:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydb

  web:
    image: php:7.4-apache
    ports:
      - "8074:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db

volumes:
  dbdata: