version: "3"

services:

  app:
    image: php:7.4-fpm
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - "8080:80"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata: